-- CRIANDO TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS CAFES.TB_PRODUTO(
PRODUTO VARCHAR(20),
NOME VARCHAR(150) NOT NULL,
EMBALAGEM VARCHAR(50) NOT NULL,
TAMANHO VARCHAR (50) NOT NULL,
SABOR VARCHAR(50) NOT NULL,
PRECO FLOAT NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (PRODUTO));

-- EXCLUINDO TABELA 
DROP TABLE IF EXISTS CAFES.TB_PRODUTO;