-- CRIANDO SCHEMA PARA BEBIDAS
CREATE SCHEMA IF NOT EXISTS BEBIDAS;

-- CRIANDO BANCO DE DADOS DENTRO DO SCHEMA
CREATE DATABASE IF NOT EXISTS CAFES;

-- Apagando banco de dados
DROP DATABASE IF EXISTS CAFES;

-- Apagando schema
DROP SCHEMA IF EXISTS BEBIDAS;